apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dm
  template:
    metadata:
      labels:
        app: dm
    spec:
      containers:
        - name: dm-container
          image: shaikmustafa/mygame
          ports:
            - containerPort: 80
